add atresplayer channels
beardypig/tv-stream-db pull request #1
Opened 2017-02-22 15:59 UTC by karlo2105

2017-02-22 16:10 UTC, beardypig commented
Awesome! Looks like I need to fix the build checking for PRs... :D 
Couple of syntax error I spotted, lemme just annotate them.

Wooo thanks! 🥇

2017-02-22 16:13 UTC, beardypig requested changes
A couple of typos :) Otherwise looks good :D

Thanks a lot :)

2017-02-22 16:13 UTC, beardypig commented on atresplayer.json
> +    "language": "esp"
There is a missing `,` on the end of the line 
```json
"language": "esp",
```

2017-02-22 16:13 UTC, beardypig commented on atresplayer.json
> +      "url": "http://www.atresplayer.com/directos/television/antena3/"},
There shouldn't be a `}` in this line:
```json
"url": "http://www.atresplayer.com/directos/television/antena3/",
```

2017-02-22 16:13 UTC, beardypig commented on atresplayer.json
> +      "url": "http://www.atresplayer.com/directos/television/lasexta/"},
Same here, an extra `}` getting in the way :)
```json
"url": "http://www.atresplayer.com/directos/television/lasexta/",
```

2017-02-22 16:13 UTC, beardypig commented on atresplayer.json
> +      "url": "http://www.atresplayer.com/directos/television/atreseries/",
Here there is a missing `}`, and the `,` is not required :)
```json
"url": "http://www.atresplayer.com/directos/television/atreseries/",
```

2017-02-22 19:23 UTC, beardypig requested changes
If you fix those two I think this is good to merge :-)

2017-02-22 19:23 UTC, beardypig commented on datafiles/streams/atresplayer.json
> +      "url": "http://www.atresplayer.com/directos/television/antena3/"},
Just seen this one with the extra `} `...

2017-02-22 19:23 UTC, beardypig commented on datafiles/streams/atresplayer.json
> +      "url": "http://www.atresplayer.com/directos/television/lasexta/"},
And the same here :-)

2017-02-22 19:36 UTC, karlo2105 commented
I pushed fixes it it ok now ?

2017-02-22 19:37 UTC, beardypig requested changes
I'm going to automate these checks :-)

2017-02-22 19:37 UTC, beardypig commented on datafiles/streams/atresplayer.json
> +        "geolocked": false},
Ah, now we are missing `}` before the `,`...

2017-02-22 19:37 UTC, beardypig commented on datafiles/streams/atresplayer.json
> +        "geolocked": false},
Same here...

2017-02-22 19:51 UTC, beardypig commented on datafiles/streams/atresplayer.json
> +        "geolocked": false},
On the `geolocked` line
```
 "geolocked": false}},
```

2017-02-22 20:10 UTC, beardypig commented
You can use this website: http://jsonlint.com to validate the json file :-)

2017-02-22 22:47 UTC, karlo2105 commented
Not sure what to do as everythings looks like ok.

```
Error: Parse error on line 14:
...		},		"attributes": {			"geolocked": 
---------------------^
Expecting 'EOF', '}', ',', ']', got ':'
```

2017-02-23 11:48 UTC, beardypig approved these changes

2017-02-23 11:48 UTC, beardypig commented
Hope you don't mind that I fixed it :)

2017-02-23 11:51 UTC, merged

2017-02-23 11:52 UTC, beardypig commented
Thanks @karlo2105 and congrats 👍

2017-02-23 12:00 UTC, karlo2105 commented
Thanks for fix I don't mind at all. 
It's just I didn't figure out what was wrong.